default: &default
  adapter: mysql2
  port: 3306
  username: bysuser
  password: bysuser
  enable_call: true
  flags: CLIENT_MULTI_RESULTS

development:
  <<: *default
  database: astra_aspira_accounting
  host: 10.228.5.81

test:
  <<: *default
  database: astra_aspira_accounting
  host: 10.228.5.81

production:
  <<: *default
  database: astra_aspira_accounting
  host: ip-10-61-145-9.ec2.internal

central_catalogue_development:
  adapter: mysql2
  database: central_catalogue
  host: 10.228.5.81
  username: bysuser
  password: bysuser
  enable_call: true
  flags: CLIENT_MULTI_RESULTS

central_catalogue_test:
  adapter: mysql2
  database: central_catalogue
  host: 10.228.5.81
  username: bysuser
  password: bysuser
  enable_call: true
  flags: CLIENT_MULTI_RESULTS

central_catalogue_production:
  adapter: mysql2
  database: central_catalogue
  host: ip-10-61-145-9.ec2.internal #prod as of 2014-04-30
  username: bysuser
  password: bysuser
  enable_call: true
  flags: CLIENT_MULTI_RESULTS
