default: &default
  adapter: mysql2
  port: 3306
  username: bysuser
  password: bysuser
  enable_call: true
  flags: CLIENT_MULTI_RESULTS

development:
  <<: *default
  database: astra_aspira_accounting
  host: 10.228.5.81

test:
  <<: *default
  database: astra_aspira_accounting
  host: 10.228.5.81

production:
  <<: *default
  database: astra_aspira_accounting
  host: ip-10-61-145-9.ec2.internal
